# Site
repository: github.com/AkazaAkane
favicon: images/favicon.ico

# Personal info
name: Yuhao Chen
title: Junior in Carnegie Mellon University
major: Economics and Statistics
email: yxckeis8@gmail.com / yuhaoc@andrew.cmu.edu
website: https://github.com/AkazaAkane

# Social links
# twitter_username: facespics
github_username:  AkazaAkane
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: yxckeis8
linkedin_username: yuhao-chen-640943119
# pinterest_username: jekyll
#youtube_username: NA
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's August (Yuhao Chen) and I'm a Junior Student in CMU. My major is Economics and Statistics. Currently, I am interested in applying data science/machine learning into education and sports(especially Esports).
  My research is about causal inference as well as causal machine learning.
  I am most skilled in: <mark>R</mark> and <mark>Python</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  I go to gym almost everyday. Besides, I love reading books and playing computer game(overwatch, LOL).
  Also, I am a typical nerd weeb who likes making Japanese food.


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
